### DISCUSSION TITLE
Kapitan Secrets and Helm integration problems

### DISCUSSION THREAD

**Discussion by Moep90** [deepmind/kapitan#712] [Q&A] [answered]
Hey,

I'm currently working on an adoption of a helmchart of goharbor.
See: https://github.com/goharbor/harbor-helm/

```yaml
parameters:
  harbor:
    chart_name: ${target_name}
    chart_version: 1.6.0
    namespace: ${namespace}
    helm_values:
      name: ${target_name}
      database:
        type: internal
        internal:
          password: ?{base64:targets/${target_name}/harbor-db-internal-password||randomstr:16}
```

This Helmchart requires plaintext passwords as value-Input.
So I tried using the kapitan's secret-backend base64 like so: 
`?{base64:targets/${target_name}/harbor-db-internal-password||randomstr:16}`

Assuming my refs `refs/targets/harbor/` is empty.
I run kapitan for the first time to generate the secrets:
`$ ./kapitan compile -t harbor`

This generates the file `refs/targets/harbor/harbor-controller-secret` with the following content:
```yaml
$ cat refs/targets/harbor/harbor-controller-secret
---
data: cTc5UmZiYm4xYWZDOXNwcA==
encoding: original
type: base64
This is exactly what I expected:
data: UmVUbFZmdTU0bFZ0NG9Caw==
encoding: original
type: base64
```

```bash
$ echo "UmVUbFZmdTU0bFZ0NG9Caw==" |base64 -d
ReTlVfu54lVt4oBk
```
But the secrets in the end looks like this:
```yaml
$ cat compiled/harbior/harbor/templates/database/database-secret.yaml
---
apiVersion: v1
data:
  POSTGRES_PASSWORD: P3tiYXNlNjQ6dGFyZ2V0cy9oYXJib3IvaGFyYm9yLWRiLWludGVybmFsLXBhc3N3b3JkfHxyYW5kb21zdHI6MTZ9
[...]
```

```bash
$ echo "P3tiYXNlNjQ6dGFyZ2V0cy9oYXJib3IvaGFyYm9yLWRiLWludGVybmFsLXBhc3N3b3JkfHxyYW5kb21zdHI6MTZ9" | base64 -d
?{base64:targets/harbor/harbor-db-internal-password||randomstr:16}
```

Any idea how I can make use of the kapitan secrets backend im cimbination with helm?
