### DISCUSSION TITLE
How the compile fetch work exactly?

### DISCUSSION THREAD

**Discussion by owlzq1** [deepmind/kapitan#719] [Q&A] [answered]
So I have multiple targets that should be provisioned with ansible. There are multiple playbooks with different tags for different kinds of clusters.
The compile part looks like this
```yaml
kapitan:
    dependencies:
    - type: git
      output_path: .ansible/a
      source: https://git.com/a
      ref: ${cluster:a_version}
    - type: git
      output_path: .ansible/b
      source: https://git.com/b
      ref: ${cluster:b_version}
    - type: git
      output_path: .ansible/c
      source: https://git.com/c
      ref: ${cluster:c_version}
```
During compile --fetch they are downloaded to root .ansible directory.
1. Do I understand correctly, this setup won't work when different targets import those dependencies as a class? I didn't get any errors but i have no idea which refs I've got after compile. I need to set different output_path for every type of cluster, right? If i delete the ref part, it only fetches the master, so i can't switch branches myself via canned scripts
Thing is, i have plenty of those, so i'll get around 40x3 replicas of almost identical repos if i'll use the option with different output path
2. I've changed the ref for the cluster, and during compile i only get 
```
Dependency https://git.com/a: fetching now
Not updating .ansible/a/smtn (file already exists)
...
```
I don't see messages that some of the files have changed. The log message makes me think that if a file exists, it won't get override even if a file has changed. What actually happens?
Also want to hear your opinion on how would you do this kind of setup.

**Comment by ademariag** [comment, marked as answer]
Discussed in channel: https://kubernetes.slack.com/archives/C981W2HD3/p1616504004042300

You can force fetch using the `--fetch` option. Also you can make it a default by changing the `.kapitan` file

```
cat .kapitan 
version: 0.29
compile:
 prune: true
 embed-refs: true
 force: true
 fetch: true
 ```
