### DISCUSSION TITLE
Secret Sub-Variables don't work

### DISCUSSION THREAD

**Discussion by owlzq1** [deepmind/kapitan#722] [Q&A] [answered]
Could you please help figure out why sub-variables don't work in the case below?
```bash
10:47:32 > kapitan --version
0.29.5
```
```bash
10:39:39 > cat ansible.yml
ansible_creds:
  user: user
  password: password
```
```bash
kapitan refs --write gkms:passwords/lab-bm -t c01 -f ansible.yml
```
```bash
10:44:45 > kapitan refs --reveal --ref-file refs/passwords/lab-bm
ansible_creds:
  user: user
  password: password
 ```
```yaml
# imported to target
parameters:
  ansible_user: ${gkms:passwords/lab-bm@ansible_creds.user||randomstr:32|base64}
  ansible_password: ${gkms:passwords/lab-bm@ansible_creds.password||randomstr:32|base64}
```
```bash
10:45:56 > kapitan compile -t c01
Inventory reclass error: -> c01
   Cannot resolve ${gkms:passwords/lab-bm@ansible_creds.user||randomstr:32|base64}, at ansible_user, in yaml_fs:///xxx/classes/env/lab.yml
   Cannot resolve ${gkms:passwords/lab-bm@ansible_creds.password||randomstr:32|base64}, at ansible_password, in yaml_fs:///xxx/classes/env/lab.yml


-> c01
   Cannot resolve ${gkms:passwords/lab-bm@ansible_creds.user||randomstr:32|base64}, at ansible_user, in yaml_fs:///xxx/classes/env/lab.yml
   Cannot resolve ${gkms:passwords/lab-bm@ansible_creds.password||randomstr:32|base64}, at ansible_password, in yaml_fs:///xxx/classes/env/lab.yml
