### DISCUSSION TITLE
number as a key converts into string after compilation

### DISCUSSION THREAD

**Discussion by owlzq1** [deepmind/kapitan#724] [Q&A]
I have the following snippet in the target:
```yaml
hosts:
  ...
    storage:
      hosts:
        c01-host0[1:3]:
          volumes:
            0:
              vg: "vg_name"
```
After compilation via jsonnet
```jsonnet
local kap = import 'lib/kapitan.libjsonnet';
local inv = kap.inventory();
{
  hosts: inv.parameters.hosts,
}
```
Or with kadet
```python
from kapitan.inputs.kadet import BaseObj, inventory
inv = inventory()


class Hosts(BaseObj):

    def body(self):
        self.root = inv.parameters.hosts


def main():
    obj = BaseObj()
    obj.root.hosts = Hosts()
    return obj
```
i got this as a result(zero in quotes):
```yaml
storage:
  hosts:
    c01-host0[1:3]:
      volumes:
        '0':
```
Which breaks the ansible deployment. The same thing happen when number is not zero.
Please advice on how to fix this.
