### ISSUE TITLE
Secret files containing multiple values / allowing GPG encrypted target files even?

### ISSUE THREAD

**Issue by frittentheke** [deepmind/kapitan#131]
When many secrets are used, gpg will be running / invoked over and over again to decrypt each an every file containing just a little string.
It is certainly inefficient to run GPG for every such little string and it clutters the classes files to add gpg and the secret path for each time.

1) What about allowing referencing sub-variables in secret files like

```
  mysql:
    storage: 10G
    storage_class: standard
    image: mysql:latest
    users:
      root:
         password: ${gpg:allmysecretsinonefile:mysql:password}

```

-- This would allow decrypting and then caching a whole file containing multiple values once and allow for much faster compiles when many secrets are used.

2) Much easier / less error-prone:

Allow using whole gpg encrypted target files which are simply decrypted prior to rendering the templates.
this could be as easy as adding ".gpg" to your target yaml file by convention. Inside the classes those variables should be addressable just like any other variable, making the fact that this is actually sourced from an encrypted file transparent.
