### ISSUE TITLE
importing helm charts support

### ISSUE THREAD

**Issue by ramaro** [deepmind/kapitan#143]

**Comment by ramaro** [comment]
The idea is to transfer the helm chart, translate variables into an inventory reclass class and yaml structure to json/jsonnet. Still uncertain about go templates support, but it will either be translated into reclass references or we'll package kapitan with the go templating library.

**Comment by uberspot** [comment]
Can be done as part of #91 . 
More info on helm issue: 
```
- make new input type called helm, 
- import helm charts, 
- behind the scenes the values of yaml file are 
  translated to inventory and then we compile the 
  golang templates library to be used with kapitan when compiling.
```

**Comment by harsh-98** [comment]
@ramaro  Can explain what you mean by `it will either be translated into reclass references or we'll package kapitan with the go templating library.` . 
Does packaging kapitan with go templates, means to create a c shared object and create python bindings for it? 
And i didn't understand the reclass references part?

**Comment by harsh-98** [comment]
I am not able to find support (or any lib) which provides bindings for go templates lib. I search on pypi and google search too. For helm, a lib named [pyhelm](https://github.com/flaper87/pyhelm) is there. It uses protoc to compile protobuf messages to python. So, that gRPC communication to tiller can happen from python. It is basically a helm client. It can load charts but it doesn't render them, just sends them to tiller where they are used.

**Comment by ramaro** [comment]
We don't want to take the tiller approach. We want instead a new helm input type which we can compile. For this we'll need to build a golang templating library that is loadable from python (c bindings).
By inventory references, I meant that values will get translated/copied into new inventory component classes (prefered) or we'll need to change kapitan to read values.yml from elsewhere other than the inventory (not great)

**Comment by caioaao** [comment]
why would we need to load values.yml into inventory? wouldn't it be easier to just make the new helm input type with options that translate to helm's cli options? For example, writing this:
```yml
parameters:
  kapitan:
    compile:
      - input_type: helm
        output_path: manifests/istio.yml
        input_path: path_to_istio/helm_package
        values_path: overrides.yml
        name: istio
        namespace: istio-system
        set_values:
          - grafana.enabled: true
          - servicegraph.enabled: true        
```

would have the same effect, when compiling, as calling helm directly like so

```bash
helm template path_to_istio/helm_package --name istio --namespace istio-system \
     --set grafana.enabled=true \
     --set servicegraph.enabled=true \
     -f overrides.yml \
     > compiled/target/manifests/istio.yml
```
