### ISSUE TITLE
b64encode jinja2 uses a wrong value of secret for encoding

### ISSUE THREAD

**Issue by metacoma** [deepmind/kapitan#210]
**Describe the bug/feature**
Wrong b64encode behavior with secrets parameters in jinja2 templating 

**To Reproduce**
1. create gpg secret
```
echo -n "dockerhub_password" | kapitan secrets -vvv --write gpg:me/dockerhub/password -t common -f -
```
2. create target with dockerhub_password parameter, for example `inventory/targets/bug` with content:
```
parameters: 
  dockerhub:
    password: "?{gpg:me/dockerhub/password}"
 kapitan:
   vars:
    target: "bug"
   compile:
     - 
       input_path: 
        - templates/dockerhub.txt
       input_type: jinja2
       output_path: "data/" 
```
`templates/dockerhub.txt` content:
```
{% set p = inventory.parameters %}
{{ p.dockerhub.password | b64encode }}
```
3. run `kapitan compile -t bug --reveal`
4. check compiled file:
`cat compiled/bug/data/dockerhub.txt`
```
P3tncGc6bWUvZG9ja2VyaHViL3Bhc3N3b3JkfQ==
```

**Expected behavior**
`cat compiled/bug/data/dockerhub.txt`
```
ZG9ja2VyaHViX3Bhc3N3b3Jk
```

b64encode function in jinja2 filter caclulate b64sum from '?{gpg:me/dockerhub/password}' value instead of 'dockerhub_password' 

```Python 3.6.7
kapitan 0.22.3
```
