### ISSUE TITLE
Load environment variables in config file (.kapitan)

### ISSUE THREAD

**Issue by prakashrj** [deepmind/kapitan#211]
It will be nice if different paths used by kapitan command can be referenced with environment variables like in the following example. 

```
compile: 
  inventory-path: $KPATH/inventory
  search-paths: 
    - $KPATH
  output-path: $KPATH

inventory: 
  inventory-path: $KPATH/inventory

searchvar: 
  inventory-path: $KPATH/inventory

secrets: 
  inventory-path: $KPATH/inventory

lint: 
  inventory-path: $KPATH/inventory
  compiled-path: $KPATH
  secrets-path: $KPATH

```
