### ISSUE TITLE
Allow wildcards or directory for compile_input path.

### ISSUE THREAD

**Issue by rbounds** [deepmind/kapitan#235]
**Describe the bug/feature**
Allow wildcards or directory for compile_input path.

It would be nice to define one class that handles inputs and outputs for everything in a directory. 
``` 
kapitan:
    compile:
      - output_path: manifests/$SUBDIRNAME/
        output_type: yaml
        input_paths:
          - components/*/*
        input_type: jsonnet
```
