### ISSUE TITLE
Support to validate the inventory before compiling

### ISSUE THREAD

**Issue by maheswarasunil** [deepmind/kapitan#258]
**Support to validate the inventory before compiling**
   We are trying to explore the options for inventory value validations. Example 
In inventory 
```
 mysql:
    storage: 10G
    storage_class: standard
    image: mysql:latest  
```
we like to validate the value of 10G before compile. 
As jsonnet is not having many libraries to support like regex validations etc. We are not able to achieve this. 
  
It would be great if we can have validation support.
