### ISSUE TITLE
Add the possibility to place compiled output in subdirectory

### ISSUE THREAD

**Issue by skinny** [deepmind/kapitan#281]
disclaimer:  I'm still very new to the project so there might be a better/other way of doing this

When I have multiple components compiled into the `compiled` output directory there is 

-  a chance of name collision if multiple components generate the same filename (e.g. service.yml)
-  a change of getting a big flat list of files of which it is hard to see which component they belong to. This can be mitigated by implementing a resource naming scheme ('component-function.yml') 

Even from a file management perspective it might be a good idea to have the option to automatically place output in different folders or maybe have an new option in the inventory files to set this.

What are your toughts ?

**Comment by uberspot** [comment]
As mentioned on slack 

> you can do this by changing the input_paths/output_path kapitan parameters
```
parameters:
  namespace: ${target}
  kapitan:
    vars:
      target: ${target}
    compile:
      - output_path: manifests/mycomponent
        output_type: yaml
        input_type: jsonnet
        input_paths:
          - components/mycomponent/main.jsonnet
```
