### ISSUE TITLE
Feature request - copying files to compiled output 

### ISSUE THREAD

**Issue by KidkArolis** [deepmind/kapitan#290]
When using some existing manifests (e.g. nginx, cert-crd, cert-manager), it would be nice to be able to drop those manifests as is into the kapitan components and then be able to copy to compiled output, e.g. manifest dir. This way, you can reuse them without modifying and still collocate with the rest of the configuration, including any templated scripts that could be used to deploy those manifests. You could even imagine (perhaps later on, once it becomes relevant to the project) using kustomize to tweak those templates or jsonnet with yaml_load whichever is more appropriate.

Right now, you can mimick this by either using yaml_load:

```
local kap = import "lib/kapitan.libjsonnet";
local inv = kap.inventory();

{
  "nginx": kap.yaml_load("./nginx.yml")
}
```

Or by "faking" them as templates, which is actually not bad:

```
parameters:
  kapitan:
    compile:
      - output_path: manifests
        output_type: yaml
        input_type: jinja2
        input_paths:
          - components/nginx/nginx.yml
```

I don't know enough about Kapitan to suggest how best this API would look like - perhaps the above existing solutions are already sufficient.

**Comment by adrianchifor** [comment]
You can do this with kadet:

```python
from kapitan.inputs.kadet import BaseOBj, inventory
inv = inventory()

class NginxContainer(BaseObj):
  def new(self):
    self.update_root("./nginx.yml")

  def body(self):
    self.root.image = inv.parameters.nginx.image

def main():
  obj = BaseOb()
  obj.root.container = NginxContainer() # will compile into container.yml
  return obj
```

```yaml
parameters:
  nginx:
    image: nginx:1.15
  kapitan:
    compile:
    - output_path: manifests
      input_type: kadet
      output_type: yaml
      input_paths:
        - components/nginx/
```
