### ISSUE TITLE
Config Map 

### ISSUE THREAD

**Issue by kapilgarg83** [deepmind/kapitan#324]
Hi,

I need to generate config map using kapitan.
Its working fine with simple key : value pair type.

But now I am implementing prometheus for same I need to create config map file for server component.

i.e output like .

```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    component: "server"
    app: prometheus
    release: release-name
    chart: prometheus-8.11.2
    heritage: Tiller
  name: release-name-prometheus-server
data:
  alerts: |
    {}
    
  prometheus.yml: |
    global:
      evaluation_interval: 1m
      scrape_interval: 1m
      scrape_timeout: 10s
    rule_files:
    - /etc/config/rules
    - /etc/config/alerts
    scrape_configs:
    - job_name: prometheus
      static_configs:
      - targets:
        - localhost:9090

 rules: |
    {}
```

but same is not working.
When I pass this value to libjsonnet function config map and try to compile I got error message.
Can any body please suggest..??

As I have big configuration data is it possible I can pass config file name ( prometheus.yml) and will get the out put in config map YML.

Thanks

**Comment by adrianchifor** [comment]
You can use jinja2 for this.

prometheus.yml.j2:
```
global:
  evaluation_interval: {{parameters.prometheus.evaluation_interval}}
  scrape_interval: {{parameters.prometheus.scrape_interval}}
  scrape_timeout: {{parameters.prometheus.scrape_timeout}}
  rule_files:
  - /etc/config/rules
  - /etc/config/alerts
  scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets:
      - localhost:9090
```

configmap.jsonnet:
```
local kap = import "lib/kapitan.libjsonnet";
local kube = import "lib/kube.libjsonnet";

{
  "prometheus_configmap.yml": kube.ConfigMap("prometheus") {
    data: {
      "prometheus.yml": kap.jinja2_template("./prometheus.yml.j2", kap.inventory()),
    },
  },
}
```

prometheus.yml (inventory):
```
parameters:
  prometheus:
    evaluation_interval: 1m
    scrape_interval: 1m
    scrape_timeout: 10s

  kapitan:
    manifests:
      - components/prometheus/configmap.jsonnet
```

**Comment by kapilgarg83** [comment]
Thanks for quick response. I tried the above steps and below is the output:


```
apiVersion: v1
data:
  prometheus.yml: "global:\n  evaluation_interval: 1m\n  scrape_interval: 1m\n  scrape_timeout:\
    \ 10s\n  rule_files:\n  - /etc/config/rules\n  - /etc/config/alerts\n  scrape_configs:\n\
    \  - job_name: prometheus\n    static_configs:\n    - targets:\n      - localhost:9090"
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    name: prometheus
  name: prometheus
  namespace: prometheus

```

any suggestion..?
