### ISSUE TITLE
Jsonnet yaml_load of multi document file

### ISSUE THREAD

**Issue by drzero42** [deepmind/kapitan#404]
**Describe the bug/feature**
I am trying to use dependency handling to download yaml manifests and jsonnet to customize the output. The upstream yaml manifest is a multidoc file, as is fairly normal for kubernetes manifests, but I can not load that into my jsonnet script to customize the output. I get this error: `expected a single document in the stream`

**To Reproduce**
I'm using metallb as an example. This is the class file:
```
parameters:
  kapitan:
    dependencies:
      - type: https
        output_path: components/metallb/metallb.yaml
        source: https://raw.githubusercontent.com/google/metallb/v0.8.1/manifests/metallb.yaml
    compile:
      - input_type: jsonnet
        input_paths:
          - components/metallb/metallb.jsonnet
        output_path: components/metallb
        output_type: yaml
```
And this is metallb.jsonnet:
```
local kap = import "lib/kapitan.libjsonnet";
local inv = kap.inventory();

local ml = kap.yaml_load("components/metallb/metallb.yaml");

{
  [x.kind + '-' + x.metadata.name]: x
  for x in ml
}
```
Then I run `kapitan compile --fetch`:
```
$ kapitan compile --fetch
Dependency components/metallb/metallb.yaml : already exists. Ignoring


Jsonnet error: failed to compile /home/abo/k8s/components/metallb/metallb.jsonnet:
 RUNTIME ERROR: Parse yaml failed to parse /home/abo/k8s/components/metallb/metallb.yaml: expected a single document in the stream
  in "<unicode string>", line 1, column 1:
    apiVersion: v1
    ^
but found another document
  in "<unicode string>", line 7, column 1:
    ---
    ^
	/tmp/_MEIdefbyb/kapitan/lib/kapitan.libjsonnet:3:21-50	function <anonymous>
	/home/abo/k8s/components/metallb/metallb.jsonnet:4:12-60	thunk <ml>
	/home/abo/k8s/components/metallb/metallb.jsonnet:8:12-14	thunk <a>
	/home/abo/k8s/components/metallb/metallb.jsonnet:(6:1)-(9:2)	function <anonymous>
	/home/abo/k8s/components/metallb/metallb.jsonnet:(6:1)-(9:2)	

Compile error: failed to compile target: cluster
```

**Expected behavior**
I should be able to load a multidoc yaml file.

** If it's a bug (please complete the following information):**
 - kapitan 0.25.1
