### ISSUE TITLE
Kapitan Secrets Controller

### ISSUE THREAD

**Issue by ademariag** [deepmind/kapitan#435]
**Describe the feature**
I would like to suggest to create a Controller that is capable of applying Kapitan secrets to a Kubernetes namespace.

The Controller could mimic/reimplement https://github.com/bitnami-labs/sealed-secrets (or even just be a patch to their already excellent solution)

# Expected behaviour
A user
* deploys the Kapitan Secrets Controller to a cluster
* Associates it with a service account capable of `roles/cloudkms.cryptoKeyDecrypter`
*  The user would then push a Kapitan Secret CRD like

```
apiVersion: v1
kind: KapitanSecret
type: Opaque
metadata:
  labels:
    name: webserver
  name: webserver
  namespace: dev
data:
  password: ?{gkms:targets/dev/secret:3663f6d7}
  secret: ?{gkms:targets/dev/secret:d507b308}
```

* Seconds after deployments, the following would appear
```
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    name: webserver
  name: webserver
  namespace: dev
data:
  password: 123 .     #base64 version
  secret: k2ppdjk2    #base64 version
```

Again, I suggest looking at https://github.com/bitnami-labs/sealed-secrets and following a similar approach.
