### ISSUE TITLE
SUGGESTION: Allow prune per compile output

### ISSUE THREAD

**Issue by ademariag** [deepmind/kapitan#444]
**Describe the bug/feature**
Sometimes global prune on/off is not enough.

I propose to add the optional "prune" option to a compile configuration:

```
    kapitan:
      compile:
        - output_path: terraform
          output_type: json
          output_prune: false
          input_paths:
            - components/terraform/main.jsonnet
          input_type: jsonnet
```

**Additional context**
In particular, to give a use case, I compile terraform together with spinnaker and kubernetes, and as for this "bug" https://github.com/terraform-providers/terraform-provider-google/issues/4431 terraform sometimes needs to see the nulls
