### ISSUE TITLE
compile --fetch does not update files

### ISSUE THREAD

**Issue by ademariag** [deepmind/kapitan#458]
**Describe the bug/feature**
When running `kapitan compile --fetch`, existing files are not updated if the remote files have changed

**To Reproduce**
1. Create a dependencies section
```
  kapitan:
    dependencies:
      - type: https
        source: https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.9.7/controller.yaml
        output_path: components/sealed_secrets/controller.yml
```
2. run `kapitan compile --fetch`
3. If the file is already present locally, it will be skipped with
```
Dependency components/sealed_secrets/controller.yml : already exists. Ignoring    
```

**Expected behavior**
If the remote file has changed, I expect the `fetch` instruction to update the local file
Possibly, we could have a flag like `force_update: true` to selectively enable this new behaviour
