### ISSUE TITLE
Display the file names which caused error in compilation

### ISSUE THREAD

**Issue by AlphaRoy14** [deepmind/kapitan#469]
**Describe the feature**
When the files in the inventory is not structured properly, `kapitan compile` outputs the message 
`Invalid inventory structure` followed by an error message. The error message, however, doesn't contain the actual path or name of the wrongly structured inventory file. Displaying the name of the file will help save a lot of time searching for it.

**To Reproduce**
1. Open a .yml file in the inventory 
2. make some changes in the parameters.kapitan.compile section.
3. E.g input_paths key expects an array, provide a single value instead 
```

parameters:
  kapitan:

    compile:

      - output_path: .
        input_type: jinja2
        input_paths:
          - templates/docs

      - output_path: manifests/html
        input_type: jinja2
        input_paths: templates/index.html

```
4. run `kapitan compile`
5. see error

**Output**
```
Invalid inventory structure

Error: 'templates/index.html' is not of type 'array'
On instance:
"templates/index.html"
```

**Expected behavior**
Error message should contain the name or path to the file.
