### ISSUE TITLE
The copy input type clobbers a directory

### ISSUE THREAD

**Issue by jmgilman** [deepmind/kapitan#536]
**Describe the bug/feature**
When the `copy` output type is given a directory to copy, the target directory will have everything inside of it clobbered. This presents an issue in the case where another compile rule is outputting to the directory that gets clobbered by the copy. 

**To Reproduce**
1. Create two compile rules: one of any other type (jsonnet, jinja2, etc.) and one of type copy
2. Have the `output_path` of both rules point to the same directory
3. Ensure the `copy` rule has an `input_source` that is a directory
4. Compile the inventory
5. The files created by the non-copy compile rule will not be present in the `output_path`

**Expected behavior**
Expected the outputs from both roles to show up in the `output_path`.

** If it's a bug (please complete the following information):**
 - `python --version`: 3.7.7
 - `pip3 --version`: 20.1.1
 - `Are you using pyenv or virtualenv?` Latest tag of Docker container

**Additional context**
Example config that will produce this bug:

```
parameters:
  kapitan:
    compile:
      - output_path: cluster
        input_type: jsonnet
        output_type: yaml
        input_paths:
          - components/cluster/main.jsonnet
      - input_type: copy
        input_paths:
          - lib/deploy
        output_path: cluster
```

The `cluster` folder will only have the contents from `lib/deploy` and not the jsonnet file generated by the other compile rule.
