### ISSUE TITLE
Improve validate to support globbed paths and autodetect kinds 

### ISSUE THREAD

**Issue by ademariag** [deepmind/kapitan#908]
**Describe the feature**
the output_paths for validate does not support globbed path, and requires indicating the kind to validate.

My propose change adds support for
* detecting globbed paths
* auto-detecting kind from loaded documents

**To Reproduce**

```
    validate:
    - type: kubernetes
      output_paths:
        - manifests/*-secret.yml
      kind: secret
      version: 1.14.0
 ```

**Expected behavior**

```
apitan compile --validate -t dev
Rendered inventory (0.08s)
Compiled dev (0.12s)


invalid 'Ingress' manifest at ./compiled/dev/manifests/global-ingress.yml
['spec', 'rules', 0, 'http', 'paths', 0] Additional properties are not allowed ('pathType' was unexpected)
['spec', 'rules', 0, 'http', 'paths', 0, 'backend'] Additional properties are not allowed ('service' was unexpected)
['spec', 'rules', 0, 'http', 'paths', 0, 'backend'] 'serviceName' is a required property
['spec', 'rules', 0, 'http', 'paths', 0, 'backend'] 'servicePort' is a required property
```
