### ISSUE TITLE
Dependency management

### ISSUE THREAD

**Issue by adrianchifor** [deepmind/kapitan#91]
We could of course use plain git submodules, but what if we only need only one file or folder from an external git repo, http url or even helm chart/templates ?

I would like to introduce the concept of modular dependencies in kapitan, and it would look something like this:

```
parameters:
  kapitan:
    compile:
    ...

    dependencies:
    - type: git
      output_path: lib
      source: git@github.com:grafana/grafonnet-lib.git
      subdir: grafonnet
      version: 0.1
    - type: http
      output_path: lib
      source: https://raw.githubusercontent.com/bitnami-labs/kube-libsonnet/master/kube.libsonnet
      version: 0.1
```

In this scenario, `kapitan compile` will pull `github.com/grafana/grafonnet-lib/grafonnet/*` and `github.com/bitnami-labs/kube-libsonnet/master/kube.libsonnet` into `lib` at the root. Dependencies will be cached and only re-pulled when the **version** changes, keeps things simple and we don't need to implement an extra kapitan subcommand.

Users have full control of what the **source** can be (jsonnet, libsonnet, jinja2 templates, k8s manifests etc.) and where it's placed inside the project (**output_path**), can be per target, class or global.

In terms of modularity, each **type** can be defined as a separate python module with the same name, as in `kapitan/kapitan/dependencies/git.py` will control the functionality of `type: git`; in the example above, **subdir** is a git module specific variable, we can also add branch, release etc.

@ademariag @gburiola @ramaro What do you think?
